import { existsSync } from "node:fs";
import { createDatabase } from "./db/pools.js";
import { readConfig } from "./config.js";
import { readPlatformConfig } from "./platform-config.js";
import { Jobs } from "./jobs.js";
import { RuntimeConfig } from "./runtime-config.js";

if (existsSync(".env")) process.loadEnvFile(".env");
const baseConfig = readConfig();
const database = createDatabase(baseConfig);
const platformConfig = readPlatformConfig();
const runtime = new RuntimeConfig(database.primary, baseConfig, platformConfig);
await runtime.load();
const configPoll = setInterval(() => { void runtime.sync().catch(() => console.error("配置热更新同步失败")); }, 2000);
configPoll.unref();
const jobs = new Jobs(database.primary, database.reader, platformConfig);
await jobs.start(true);
let stopping = false;
const stop = async () => { if (stopping) return; stopping = true; clearInterval(configPoll); await jobs.stop(); await database.close(); };
process.once("SIGINT", () => { void stop(); });
process.once("SIGTERM", () => { void stop(); });
